### ISSUE TITLE
指标计算问题

### ISSUE THREAD

**Issue by ohhhh2022** [j1o2h3n/DDSTGCN#2]
作者您好，很荣幸能读到您的论文，想请教一下指标的问题，在您提供的论文和代码中的MAE,RMSE指标中，15min，30min和60min计算的是该时刻的值，还是该时间窗口的平均值？我看在您提供的代码中最后test输出时，有分别输出12个时间步的指标，最后还计算了平均值，在论文中采用的是哪个指标呢？时间窗口的平均？还是单纯的该时刻的值？期待您的解答。

**Comment by j1o2h3n** [comment]
您好，感谢您的提问，您所指出的计算指标方式在论文中都有使用，在table iii中metra-la和pems-bay数据集上使用的是15、30、60min时刻的指标指，table iv中pems03、04、07、08数据集上使用的是一个小时时间窗口的平均指标值。在不同数据集上采用了不同指标值方式是为了方便与原始数据集上其它论文方法做对比。

**Comment by ohhhh2022** [comment]
感谢您的回答。
