### ISSUE TITLE
数据集pkl文件

### ISSUE THREAD

**Issue by zhoujiajie-z** [j1o2h3n/DDSTGCN#3]
作者您好，想请教一下pems数据集中的pkl文件值，通常情况下我们使用的pkl文件为单个列表170*170的矩阵，但是文中给出的文件中有两个列表，想请问下两个列表的值分别代表什么，是与超图有关吗？期待您的解答～

**Comment by j1o2h3n** [comment]
您好，关于您提到的"文中给出的文件中有两个列表"，我没明白您说的两个列表具体是指哪个地方的内容，您能详细描述下吗？谢谢

**Comment by zhoujiajie-z** [comment]
<img width="1312" alt="Snipaste_2023-12-06_00-43-58" src="https://github.com/j1o2h3n/DDSTGCN/assets/65545413/c5fd9cfd-0531-4671-b39f-52223e025b30">
代码中的adj_mx 对应的pkl文件，有两个list值，因为通常情况下使用的pkl文件都是一个list嘛 所以想请问下这两个list值对应的值是什么

**Comment by zhoujiajie-z** [comment]
<img width="873" alt="image" src="https://github.com/j1o2h3n/DDSTGCN/assets/65545413/12e6ef11-21d5-4dbd-8e38-fabaf54ef39c">
具体在代码这个load部分

**Comment by j1o2h3n** [comment]
好的，关于您提到的pkl文件，存储的是您所述的单个列表170*170的矩阵，您可以单独load进行查看。util.load_adj是对读取的pkl矩阵进行有处理操作，在里面添加了转置矩阵，您可以在util.py文件下第80行找到load_adj函数。

> <img alt="image" width="873" src="https://private-user-images.githubusercontent.com/65545413/288134569-12e6ef11-21d5-4dbd-8e38-fabaf54ef39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MzA5MTYsIm5iZiI6MTcwMTgzMDYxNiwicGF0aCI6Ii82NTU0NTQxMy8yODgxMzQ1NjktMTJlNmVmMTEtMjFkNS00ZGJkLThlMzgtZmFiYWY1NGVmMzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAyNDMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyY2FkZTg1ZWY2M2UzMzZkYzM4NmQzODU4ZTFjZDc0OWQyZjliODUzNzZlZDc2MWIwMjZhNjA2NmU1ZDAxOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g62vxmVdCgSuom0B7W3JLhdSioWKSaBXP4Nd8RWI8aU"> 具体在代码这个load部分

**Comment by zhoujiajie-z** [comment]
好滴 我去看一下 谢谢您的解答！
